### ISSUE TITLE
Wipe cached user values when updating profile

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#103]
- Go to edit profile
- Change email.
- Saved
- Go to home
- Go back to edit profile

Expected: shows new email
Actual: show old email

**Comment by rjmackay** [comment]
Actually this gets worse. If you log out and back in - the email stays reverted.
Super confusing and broken

**Comment by willdoran** [comment]
This was caused by the user cache, I've changed the user-profile to use getFresh instead.
