### ISSUE TITLE
Fix sending coverage stats to coveralls

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#1071]
### Expected behaviour
Coverage stats send to coveralls successfully

### Actual behaviour
https://travis-ci.org/ushahidi/platform-client/builds/363337609
^ `gulp send-stats-to-coveralls` fails with 
`[22:37:40] Error: Cannot find module 'gulp-coveralls'`

**Comment by rjmackay** [comment]
@crcommons This explains our broken coverage stats. The stats get generated but are never sent to the tracker. Do you think this can be resolved in cycle 3?
Its not needed for the baselines, but just for tracking overtime.

**Comment by caharding** [comment]
@crcommons was this addressed in the cycle or should move to next/

**Comment by crcommons** [comment]
@caharding It should be moved to next cycle.

**Comment by rowasc** [comment]
We have the stats now in each PR. Closing
