### ISSUE TITLE
Increase checkbox and radio-button-size (HDX) in PL

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-client#1108]
## Todo
- Adjust styles for checkbox in "Fragments" http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/
- [ ] Checkboxes to increase in size (.ltr-namespace input[type="checkbox"], .ltr-namespace input[type="radio"] width & height suggested increase to 20px. Numbers may need aligning too.

![Screen Shot 2018-04-24 at 16.30.53.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e0523026-3058-4ce9-a6cb-e35338c44f75)

- Double-check that this does not mess up list-items and modals where checkboxes are used

**Comment by Angamanga** [comment]
@Erioldoesdesign Is this an platform-wide change or just for HDX?

**Comment by Erioldoesdesign** [comment]
@Angamanga If it doesn't break anything in the wider platform where it's shown I'm in favour of rolling it out wider. 

However! there are new styles coming in via UI refactor that address some of the accessibility issues so if it's easier/quicker for now to just restrict to HDX that's fine too.

So it's about whether platform-wide change will take (in your opinion) longer than it's worth before the platform UI refactor
