### ISSUE TITLE
Adjust option-drop-down list for HDX in PL

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-client#1112]
## Todo
- [ ] Add a new dropdown to "Fragments" http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/
- [ ] An option in a drop down list that has already been chosen should not be selectable and appear at 40% opacity. 

![Screen Shot 2018-04-24 at 16.35.23.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/524b9f8c-2c95-449f-bee6-3f70b9e1b499)

**Comment by Angamanga** [comment]
@Erioldoesdesign In the designs, the text is bold in the dropdown. I cannot make this with css only, the dropdowns are incredibly hard to style. I could look for an external library for this but want to double-check first. Is it ok to keep the text in normal-weight like this instead:

![Screen Shot 2018-05-03 at 14.02.23.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/e98fbeb7-64ac-4d37-933f-4f288f549235)

**Comment by Erioldoesdesign** [comment]
@Angamanga That is totally fine :) If any of the styling is extremely hard to achieve we can make do for v0 (and possibly v1 too)

Can we capture this as a new improvement ticket to go into the backlog though? So it doesn't get lost in the ether and we capture the desire to style drop-down content at a future date?

**Comment by Angamanga** [comment]
@Erioldoesdesign Thanks, i'll add a new ticket for the improvement!
