### ISSUE TITLE
Add layouts for HDX to PL

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-client#1114]
## Adjust layouts in settings 
Using the components built in this epic, add layouts and links to layouts (http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/) for:
- [x] Adjust text in settings-menu (https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/)
- [x] Add Configure HDX page https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/acd8beb3-1a1e-436f-b887-c27f40f617f6/Configure-HDX-API
- [ ] Adjust data-export-page https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/895ab0f6-bb8f-49b9-a46b-2f36a42be8a2/-HDX-Data-Source-NOT-configured
- [ ]Adjust data-export-history-page https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/d204535d-c71b-4c3e-ab55-df51d1bdc949/HDX-Export-history
- [ ] Add layout for tagging data https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9a17d59a-cdfd-4ed4-aec5-573cdfeadb97/Data-export-HDX-single-survey
- [ ] 'Add details' page before final HDX upload includes a HDX logo in the top right https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20

**Comment by Angamanga** [comment]
@Erioldoesdesign Do you have the logo for HDX somewhere?

**Comment by Erioldoesdesign** [comment]
@Angamanga 

I have this one I pulled down from google image search that's a transparent .png and fairly large size: https://drive.google.com/file/d/1_WeyFLJT_fxC9nsARnQwLohS8bUEQme2/view?usp=sharing
