### ISSUE TITLE
Readme needs to be updated 

### ISSUE THREAD

**Issue by NidhiKJha** [ushahidi/platform-client#1289]
In the develop and epic/js-rewrite-2547 branch.
The ReadMe page says to run the project localhost:8080 but it no longer responds on that server.

Instead we should be using 
`localhost:3000`
`localhost:3001`

![issuehid1](https://user-images.githubusercontent.com/39872794/54340433-5b596980-465d-11e9-8b66-d5dc31b8d3d1.png)

![host3000](https://user-images.githubusercontent.com/39872794/54340721-010cd880-465e-11e9-83ff-830ecf746d98.png)

**Comment by vaarigupta** [comment]
Hello Can I start working on this issue?
