### ISSUE TITLE
Order of +settings menu

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-client#143]
### Expected behaviour
Through giving several product walkthroughs, I intuitively want to set my deployment up in the following order:
1. General settings
2. Map settings
3. Roles
4. Users
5. Post types
6. Categories
7. Data sources
8. Data import
9. Plan 

### Actual behaviour
Currently, if I set up in order of the settings menu, I perform set up in this order:
1. General settings
2. Map settings
3. Data sources
4. Data import
5. Post types
6. Categories
7. Users
8. Roles
9. Plan

### Steps to reproduce the behaviour/error
1. Set up a test deployment
2. Conduct a walk through of the platform set up with Shadrock

**Comment by jshorland** [comment]
I *think* this is addressed with mustang designs. cc: @brandonrosage

**Comment by brandonrosage** [comment]
It is. In fact, a lot of the Settings mode is stubbed out. Every top-level item's landing page is represented (with the only exception being Categories).
