### ISSUE TITLE
Clarification of "radio", "select", "checkbox", and "related post" in add field selection box

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-client#144]
### Expected behaviour
As a user, I should know what each of these is, the difference between them, and the appropriate use of them so I can make the right selection for my data field. Icons/images may help clarify instead of just text?

### Actual behaviour
I read the text "radio", "select,",  "checkbox", and "related post" and I am confused and have to ask questions about what they are and how they work. 

### Steps to reproduce the behaviour/error
1. Log in to a deployment as a user with the ability to manage post types
2. Edit "basic post"
3. Add field to structure step
4. See screen shot

![screen shot 2016-03-22 at 2 37 25 pm](https://cloud.githubusercontent.com/assets/3224856/13963897/b7f07310-f03d-11e5-82a7-cbb31380bd3f.png)

Note: during product demos and walk throughs, this has been a consistent question from users.  @brandonrosage curious what you think -- I'm imagining we should consider aligning this with new UX

**Comment by rjmackay** [comment]
Related to #773

**Comment by aoduor** [comment]
Hey folks, just adding in my voice here. What's our intended course of action for this :)?

**Comment by rjmackay** [comment]
Assigning to @jshorland to decide if/when this goes into a sprint

**Comment by jshorland** [comment]
cc: @brandonrosage this is fixed by mustang.

**Comment by jshorland** [comment]
Also closing in favor of #773
