### ISSUE TITLE
Save Post does not run any validation in /posts/create

### ISSUE THREAD

**Issue by ihatehandles** [ushahidi/platform-client#147]
### Expected behaviour

If the title is too short, or if there is a 'required' step that must be marked completed, or if there are some required fields - then the new post should not be saved

### Actual behaviour

I'm able to save a post that has no title or any other content whatsover

### Steps to reproduce the behaviour/error

- Click 'Add Post' on your deployment
- Click 'Save Post'

Another thing to note is the validation seems to (haven't confirmed enough) run and show error messages when I change the current selection in the *Who can see this* dropdown.

**Comment by rjmackay** [comment]
Hrm.. that odd. In general posts are validated on publication, ie. so you can create a draft and complete it later. But the UX for this is weird.
We should rethink the flow here.

**Comment by rjmackay** [comment]
@brandonrosage This and #148 show some kind janky UX when creating and saving posts that not really whats expected. Probably not what you had in mind.
Could we walk through it at some point and figure out how it *should* work?

**Comment by rjmackay** [comment]
cc @jshorland

**Comment by brandonrosage** [comment]
In the Pattern Library, [the "Post: Add" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html) demonstrates the form as it might appear to a user who had permission to post to a survey that required "review" before its could be "published." It also assumes a scenario where the user does not have permission to change the post's status (e.g. Published, Under review, Archived), nor can they contribute to the post's "Tasks" (e.g. Verification, Translation).

So, in short, they get:
- a simple form
- a disclaimer that "this post will need to be reviewed before it's published" 
- a "Submit" button

![Post add screen](https://cloud.githubusercontent.com/assets/1136279/16494101/ae3e0616-3ead-11e6-857c-28ed50175ff8.png)

If they had additional permissions, they'd simply have access to those controls. It wouldn't change the flow. 

If they have permission to review the survey's posts -- and they're adding a new post -- they'd be able to toggle the post's status from the "Post: Add" screen:

![status](https://cloud.githubusercontent.com/assets/1136279/16495045/51de0f7a-3eb1-11e6-88b2-bca30635ad21.png)

Similarly, if they had permission to contribute to the survey's post tasks -- and went to add a post -- those Tasks would appear below the survey form, editable:

![tasks](https://cloud.githubusercontent.com/assets/1136279/16495066/66b24290-3eb1-11e6-87dc-cdd88f57a92f.png)

(How they appear on the screen is also demonstrated in [the "Post: Edit" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html#tasks-verify).)

## Validation

If the user went to "Submit" a new post (or "Save" an existing post) and a required field wasn't completed, that action would be interrupted by a "Message." They wouldn't be passed along to a new page or URL. They'd remain on the "Post: Add" screen with a message explaining why the post can't be submitted, with a suggested action:

![message](https://cloud.githubusercontent.com/assets/1136279/16494307/76b50658-3eae-11e6-9a0c-889440b5258f.png)

The example above can be demonstrated on [the "Post: Add" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html) by simply selecting the "Submit" button. Furthermore, you can select the "Edit field" button in the message, and it'll navigate you to that field on the page.

If the post's form data is valid, however, the post should be saved and one of two things happens:

1. If the user is anonymous (not logged in), they'll be returned to the URL they launched "Post: Add" from (e.g. Map, Timeline) and delivered an expiring message _on that page_, like, "Your post was submitted successfully and will be reviewed before it's published."
2. If the user is logged in, they'll be taken to their new post's detail view (which is accessible to the author and any roles with permission to review it) and delivered the same expiring message _on that page_, with the added optional action to "Edit post," in case they see any mistakes and want to revise them before the post is reviewed.

_Example:_
![confirmation message](https://cloud.githubusercontent.com/assets/1136279/16494941/e77d4cf4-3eb0-11e6-830b-4ff4f9289753.png)

I think that about accounts for the meat of the "Post: Add" UX and flow. Am I overlooking anything here, @rjmackay?

**Comment by rjmackay** [comment]
If a Post field is required, we validate that when creating or editing a post. However if a Task's field is required.. when do we validate that? Do we validate it only when the task is marked complete? or on every save? 
If a task is not required but has required fields, can a user publish the post without filling those fields? In this situation how do we communicate whats required or not.

**Comment by brandonrosage** [comment]
Great question, @rjmackay. I'd suggest we validate task-related forms when they're _marked as complete_.

It's implied in adding a post that, when you select "Submit," you're saying "I'm completing the task of adding this post." But because tasks include the added control for explicitly saying "I've completed this task," I think we have to wait until that's done before we validate that task's form -- just as we wait until the author selects "Submit" to validate their post's form.
