### ISSUE TITLE
'Who can see this' dropdown is running validation in /posts/create

### ISSUE THREAD

**Issue by ihatehandles** [ushahidi/platform-client#148]
### Expected behaviour

It must silently allow the user to pick whatever value they want

### Actual behaviour

It also runs validations, showing things such as:

> To publish a post all required steps must be marked as complete. The required step Summary has not yet been marked complete

in a dialog, which is confusing since that's not its job but the [Save Post button's](https://github.com/ushahidi/platform-client/issues/147)

### Steps to reproduce the behaviour/error

- Click 'ADD POST' in your deployment
- If you have a required step, pick any value from the *Who can see this* dropdown

**Comment by rjmackay** [comment]
This isn't really a bug.. but it is a weird UX.
Because 'who can see this' sets a post to public (or not) it has to check if required field are completed.. however theres definitely got to be a more sane way to handle this.

**Comment by rjmackay** [comment]
@jshorland over to you for triage. I'd say we should drop this into a sprint soon-ish?

**Comment by rjmackay** [comment]
Fixed now.
