### ISSUE TITLE
Step-completion status indicator must not have a pointer cursor if it's not meant to be clicked on

### ISSUE THREAD

**Issue by ihatehandles** [ushahidi/platform-client#149]
### Expected behaviour

In /posts/create there is a completion status indicator to the right of every step name. It shows a tick when the user has marked the step as completed. The user cannot interact with it directly to - for example - mark a step as completed.

### Actual behaviour

When the user hovers the indicator it shows a pointer cursor as if the user can/should click on it

### Steps to reproduce the behaviour/error

Hover over the status indicator on the Create Post page

**Comment by rjmackay** [comment]
@middle8media assigning to you just for thoughts on the best fix/if this should be fixed

**Comment by middle8media** [comment]
@brandonrosage I think this is best solved by removing the cursor. Thoughts?

**Comment by brandonrosage** [comment]
No. 1, [going forward](https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926), the "Post" task itself is not governed by any sort of "completed" status. This is replaced by a simpler, top-level status for the whole post: Published, Under Review, or Archived. That status will help determine the visibility of the post.

No. 2, I've revised the PL to display a `not-allowed` cursor over disabled toggle switches.

No. 3, I think we should add a parameter for each Task (e.g. Verification) that determines which Roles can see it, *and* which Roles can edit it. This would ensure that, if a Survey had no intention for the contributors themselves to verify it, they'd never be presented with that part of the Survey form. But it'd also leave the ability to display that information to users in "Post: Detail", even if they can't edit it in "Post: Edit."

What say you, @rjmackay?

**Comment by rjmackay** [comment]
- Definitely agreed on no 1 and 2.
- Re no 3. I think the way you've proposed tasks - as separate from the "Post" itself - makes more sense.
  - However steps have changed from merely groups of fields into something else. I'm not entirely sure the transition will make sense to users with existing steps/tasks. ie. they may find they would now prefer to move fields from task to the main post.
  - I'll run some stats on number of users with more than one step in their form to see if this is a serious concern. We could potentially merge all existing fields into the "Post" itself..
- Tasks currently have a option to _require the task is complete_ before the post is published. Does that still make sense?
