### ISSUE TITLE
Some buttons do not have UI feedback when they are performing their operations

### ISSUE THREAD

**Issue by ihatehandles** [ushahidi/platform-client#150]
### Expected behaviour

Buttons like the Login button and several others notify the user when they're working via a spinning cog and other cosmetics.

### Actual behaviour

However, some buttons within the app do not - which can lead to the user thinking the press wasn't successful and click again (double submissions) etc. There aren't that many buttons which have the issue, although I can't say I've tested every button.

### Steps to reproduce the behaviour/error

Affected buttons:

- Location search button in /posts/create
- `Save Post Step` button in Add Post Step
- `Save & Close` button in /settings/forms/x
- `Save Post Type` button in /settings/forms/x
- `Save Collection` button in /collections/x

**Comment by rjmackay** [comment]
Would happily take a pull request for this if you want to fix it :)

**Comment by ihatehandles** [comment]
Tomorrow, if I can fix npm issues on my machine in time ;)
