### ISSUE TITLE
Map view UI bug on ipad screen size

### ISSUE THREAD

**Issue by yuchenglin** [ushahidi/platform-client#274]
### Expected behaviour
![screen shot 2016-06-29 at 3 25 17 pm](https://cloud.githubusercontent.com/assets/5432898/16443886/c6e7ed76-3e0d-11e6-9468-779bc32268f5.png)
### Actual behaviour
![screen shot 2016-06-29 at 3 24 20 pm](https://cloud.githubusercontent.com/assets/5432898/16443863/993ff738-3e0d-11e6-957f-7cde3a40b55c.png)
### Steps to reproduce the behaviour/error
When I test the map view in **IPad screen size 768*1024**, the add post button will overlay on the zoom in/ zoom out button.

**Comment by brandonrosage** [comment]
Fixed in the Pattern Library

**Comment by rjmackay** [comment]
CSS only fix? or HTML too?

**Comment by brandonrosage** [comment]
CSS only.
