### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by derDieDasJojo** [ushahidi/platform-client#289]
### Expected behaviour
i folowed the guide on:https://www.ushahidi.com/support/install-ushahidi
but on ```./bin/update ``` i get the following error:
```
 [InvalidArgumentException]                                                   
  There was a problem creating the schema table: SQLSTATE[42000]: Syntax erro  
  r or access violation: 1067 Invalid default value for 'end_time'   
```
so the database scheme seems to be corrupt in the current version

**Comment by rjmackay** [comment]
Can you tell me what mysql version you're running on? 
Is there any more info in that error? Can you try running `./bin/phinx migrate -c application/phinx.php -vv` and copy the output?

**Comment by fegul** [comment]
This issue is related to the one I had opened in the platform repo: https://github.com/ushahidi/platform/issues/1177

Basically, the default MySQL mode includes a mode that needs to be manually removed. This can also be fixed within the migration by providing a proper default value.

**Comment by rjmackay** [comment]
I think this is part of MySQL strict mode? the use of that was intentional.. however it looks like we must not be using it in some places (ie. testing) for this to have slipped though. 
Needs some further investigation.
