### ISSUE TITLE
Locale file is not updated on transifex

### ISSUE THREAD

**Issue by yuchenglin** [ushahidi/platform-client#295]
`app/common/locales/en.json` and `en.json` on [Ushahidi transifex](https://www.transifex.com/ushahidi/ushahidi-v3/language/en_US/) are not match.

I downloaded the translations from transifex using the gulp task. But there are different josn structures in two files and only partial translation on the UI.

**Comment by rjmackay** [comment]
@yuchenglin I think I've fixed this. Transifex had stopped auto-updating the source files for some reason. Let me know if you see the issue again.

**Comment by yuchenglin** [comment]
Thanks a lot. I saw the updated source file on Transifex!!
