### ISSUE TITLE
nothing happens when i click on "+" to add a post

### ISSUE THREAD

**Issue by derDieDasJojo** [ushahidi/platform-client#303]
### Expected behaviour
it should act like a link on: posts/create/1 and open that page.
### Actual behaviour
the button "+" turns to an "x" but no page is loaded and nothing happens.
### Research ###
i looked it up in html, but it is no link, so the forwarding seems to work via angularjs.
but i dont get, why it is not working.
if i manually call posts/create/1 i can load the page. but the button does not work .
### Steps to reproduce the behaviour/error
```
git clone https://github.com/derDieDasJojo/docker-ushahidi
cd docker-ushahidi
docker-compose up
```

#### Question ###
What could be the reason ? what can i try ? what can i do ?

**Comment by rjmackay** [comment]
Are you seeing any JS errors? If you watch the network tab is it trying to load something and failing?

**Comment by derDieDasJojo** [comment]
ok, it was something configured wrong.
tried it with another setup again and it worked.
can not exactly say what i did wrong, but anyway..
