### ISSUE TITLE
No notification when location search returns nothing on `/posts/create`

### ISSUE THREAD

**Issue by zhalloran** [ushahidi/platform-client#319]
### Expected behaviour

When search for a location against https://nominatim.openstreetmap.org/search returns an empty response, the user should receive a notification that no location was found to explain why no pin was added to the map.
### Actual behaviour

The user is given no explanation for why a pin has not been added to the map. Effectively it fails silently.
### Steps to reproduce the behaviour/error

Create or update a post and search for a nonsense location. I discovered this by searching for a real world location that is not in the nominatim search.

**Comment by rjmackay** [comment]
- The code for this is https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-location.directive.js#L106
- As an interrim solution we should just make a call to [Notify.error](https://github.com/ushahidi/platform-client/blob/develop/app/common/notifications/notify.service.js#L28) and let the user know there was no result
- Further changes are coming in another ticket so *do not overdo this*
