### ISSUE TITLE
Unable to collect tweets

### ISSUE THREAD

**Issue by Nesp** [ushahidi/platform-client#377]
### Expected behavior

I set up the twitter application following the instructions. Then I added all the required keys. It should map the tweets I am posting with the keywords I selected (geolocation is activated).
### Actual behavior

The tweets are not mapped. I tried also in Crowdmap classic, but it does not work. Then, I found out that in the Twitter application manager when I click  "Test OAuth", it tells me that the access has been denied. I am not sure if it has to deal with my twitter account. 

![d3b828a20dc6f218e093de7cba66aa4bae076c67](https://cloud.githubusercontent.com/assets/12881499/19558225/9950ea06-96c9-11e6-8064-aa8c96279a17.jpg)
### Steps to reproduce the behavior/error

Could you please help me?

**Comment by rjmackay** [comment]
Very old issue. Closing
