### ISSUE TITLE
Update views to layout-X classes

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#40]
@brandonrosage Removed the need for: 

* the class name `has-aside` (because the layout doesn't always have an aside).
* the `data-view` attribute appended to the `tabs-with-filter` pattern, establishing a view context.

Instead, I'm adhering even more strictly to the three main layouts: A, B. and C. The `<main class="page-content">` element has one of the following treatments in order to dictate how filters display (among many other things):

* `<main class="page-content">`: Patterns will be displayed in the default "Layout A" treatment.
* `<main class="page-content layout-b">`: Patterns will be displayed in the "Layout B" treatment, which leaves room to the right for either sidebar content or a filters control.
* `<main class="page-content layout-c">`: Patterns will be displayed in the "Layout C" treatment, which assumes the use of `.vertical-tabs` to prominently display page content (namely, post detail information).

**Comment by jshorland** [comment]
Closing in favor of Mustang patterns.
