### ISSUE TITLE
Published single reports showing up twice on map

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform-client#401]
### Expected behaviour
A published report will show up once on a map

### Actual behaviour
There is a report i just published in Arkansas in “Other” Survey. It is just one report, and only coming up as one on Timeline. But on my Map it is showing up twice, and showing two of the same report in the same place.

### Steps to reproduce the behaviour/error
Go to usaelectionmonitor.ushahidi.io
look at arkansas on the map and look at both posts there and see they are the same. Then look at timeline, and see only 1 post there

![screen shot 2016-11-03 at 11 51 15 am](https://cloud.githubusercontent.com/assets/2200987/19980623/f68efba2-a1bb-11e6-95bd-55fba4cc4eb3.png)

**Comment by rjmackay** [comment]
Ah. This is probably because we keep the twitter location even if a new location is added. We need to figure out a way to hide or remove that original location
