### ISSUE TITLE
Can't complete step on post

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#42]
A users reported that they can't the 'mark completed' button never becomes clickable on their posts. I noticed similar on Ushahidi.io
Need to verify if this happens on master, or is already fixed

**Comment by puffadder** [comment]
I see this problem when I specify "Location" filed as required. If I make it optional I'm able to mark it as complete.

**Comment by willdoran** [comment]
There were missing attributes for some of the field types, date, datetime and checkbox. Those are fixed in the current version of develop. Location is working for me but that might have been fixed already in the interim.
