### ISSUE TITLE
Only include "applied-filters" container if filters are present

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-client#48]
The layout for any "All Posts" views is currently incorrect because [it includes the (empty) "applied-filters" container](https://github.com/ushahidi/platform-client/blob/8d49ab6d4b9774f29cd729e7d6f00dd05a7fa394/server/www/templates/posts/views.html#L4-L7) below the page title. 

This empty container includes padding, margin, and a border that's not wanted on a view with no filters:

![image](https://cloud.githubusercontent.com/assets/1136279/11337660/3750c080-91b4-11e5-9e58-2738ba6c7c9f.png)

The intended layout is for the "applied-filters" container to be present **only if one or more filters are present**. When it's absent, we get the following intended display result:

![image](https://cloud.githubusercontent.com/assets/1136279/11337697/85fdbf9e-91b4-11e5-8a5a-deb5f71a348c.png)

Please let me know if this is in any way unreasonable.

**Comment by rjmackay** [comment]
its a fiddly thing to fix just because of the way we structured things on the Angular side.. but thats our bad not yours. We'll review the structure and figure out a fix..
