### ISSUE TITLE
Not translatable string in Surveys.

### ISSUE THREAD

**Issue by hydrosIII** [ushahidi/platform-client#530]
### Expected behaviour

The string " Add Photo" that you can see in the image is not translatable as it does not appear in the en.json file available here and in transifex. It should be translatable.

### Actual behaviour

"Add Photo" is not translatable.

### Steps to reproduce the behaviour/error
![captura de pantalla de 2017-01-28 17-50-34](https://cloud.githubusercontent.com/assets/7807363/22400717/6fe69dfc-e582-11e6-9b4b-9f5d230bfe59.png)

**Comment by jshorland** [comment]
@Angamanga i'm not sure how to QA this -- should it just go straight into "ready to deploy"?
