### ISSUE TITLE
Some content doesn't load sometimes

### ISSUE THREAD

**Issue by aaly-tgm** [ushahidi/platform-client#63]
First image:
Content of Saved Searches and Collections is not loadded
![screenshot_3](https://cloud.githubusercontent.com/assets/2486446/12293125/a7e22978-b9f1-11e5-8af2-390a80275be9.png)

Secound image:
After one or couple of refreshes of the website the content of Saved Searches and/or Collections will be back
![screenshot_4](https://cloud.githubusercontent.com/assets/2486446/12293126/a82d38a0-b9f1-11e5-95b1-95453929c5e2.png)

**Comment by aaly-tgm** [comment]
Same here:
![screenshot_5](https://cloud.githubusercontent.com/assets/2486446/12293213/3e4f520a-b9f2-11e5-822a-0d228e76a138.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/2486446/12293214/3e6be05a-b9f2-11e5-860e-681c60b228eb.png)

**Comment by rjmackay** [comment]
Those bits of content will all be loaded in the background. Its possible some requests are failing.
Was this on a reliable internet connection?
