### ISSUE TITLE
 Ushahidi Phabricator Readme link broken

### ISSUE THREAD

**Issue by boshika** [ushahidi/platform-client#643]
Clicking on Ushahidi Phabricator in the Readme should direct you to https://phabricator.ushahidi.com/

Throws "Failed to load resource: net::ERR_CONNECTION_REFUSED"

Go to Readme -> click on Ushahidi Phabricator

**Comment by rjmackay** [comment]
Thanks. I've removed the link now, we don't use Phabricator anymore
