### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by AnandPilania** [ushahidi/platform-client#685]
npm install =>
...
npm http fetch GET 304 https://registry.npmjs.org/stream-counter 876ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/babel-core 166ms (from cache)
npm verb stack SyntaxError: Unexpected end of input at 1:219420
npm verb stack irectories":{},"dist":{"shasum":"26c5b5c3152177d93f2ac0749486af1f3b03
npm verb stack                                                                                                                ^

**Comment by rowasc** [comment]
HI @AnandPilania 
Are you still facing this issue?
if the answer is yes:
- what version of npm and node are you running ?
- are you in a clean branch/tag? (`npm verb stack SyntaxError: Unexpected end of input at 1:219420` > this sounds like something that was changed locally and caused an error)

just trying to help debug this..
