### ISSUE TITLE
Language is not changing

### ISSUE THREAD

**Issue by lupa18** [ushahidi/platform-client#69]
We are trying to change language to another than English, ie, Spanish Paraguay or Spanish (Spain).

Steps to reproduce: 
1. Go to admin
2. Change language
3. Save

And nothing happen. 
 
Ushahidi version: latest (github)

Image: 

![seleccion_038](https://cloud.githubusercontent.com/assets/463429/12590642/c4e1525a-c442-11e5-98e8-0cacccb490a5.jpg)

**Comment by willdoran** [comment]
I'm going to add to this ticket that the languages displayed as available in client should be limited to those with full translations and an explanatory note should be added linking to the transifex site to allow people to contribute to lang translation.

**Comment by lupa18** [comment]
Then I tried to manual download languages with lot of work. Then I got the .js languages but couldn't did it wokrs :(

**Comment by lupa18** [comment]
Hello ! The problem is that gulp's task for download and install languages is not working. 

The workaround is install transifex client and manual download lang files: 
**1.** Install:
```
pip install transifex-client
pip install transifex-client --upgrade
```
**2.** Set & download
```
cd <root of uhsahidi>
tx init
tx set --auto-remote https://www.transifex.com/projects/p/ushahidi-v3
tx pull -a
mv translations/ushahidi-v3.client-en/* server/www/locales/
```
(in this step transifex credentials will be as

**obs:** If you get an "six" error or "urrlib3" error you must uninstall and install pip with easy_install

**Comment by plakhin** [comment]
@lupa18 
I'm getting `ValueError: Invalid IPv6 URL`. Tried python 2.7.11 and 3.4

```
stan@ubuntu.dev:~/www/map.adilsoz.dev/platform-client$ tx init
Creating .tx folder...
Transifex instance [https://www.transifex.com]:
Creating skeleton...
Creating config file...
ValueError: Invalid IPv6 URL
```

Can you please suggest any solution?

**Comment by plakhin** [comment]
@lupa18 

Did everything as you wrote, but "SITE LANGUAGE" dropdown on Settings > General Settings page is empty. https://www.dropbox.com/s/wqtf8ivqkpxv5sf/Screenshot%202016-04-21%2018.33.47.png?dl=0

I would very appreciate any help on this issus.

Thank you

**Comment by jshorland** [comment]
This is fixed. Can I close?

**Comment by willdoran** [comment]
Yep, closing
