### ISSUE TITLE
Add Survey menu UI needs to be updated

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#696]
### Expected behavior

![image](https://user-images.githubusercontent.com/1033332/28430464-a4f9f7a6-6d4e-11e7-8a81-483f817eae8b.png)

https://github.com/ushahidi/platform-pattern-library-fix-our-environment/blob/master/assets/templates/_Modals.hbs#L1216-L1235

### Actual behavior

![image](https://user-images.githubusercontent.com/1033332/28430481-b08bf628-6d4e-11e7-957a-e69b9bb00165.png)

### Steps to reproduce the behavior/error
Click the add survey button. The old actual behavior needs to be replaced with the expected behavior

Refs https://github.com/ushahidi/platform-client-fix-our-environment/issues/4

**Comment by ryanchristo** [comment]
@rjmackay The links above are broken. I was able to find the intended link for the first but not sure about the second. Is the main reason for replacing the old with the new is that the old does not allow for the user to scroll if the list is longer than the space provided? Does this work?

![](http://recordit.co/VlSjSIuEJo.gif)

**Comment by rjmackay** [comment]
That looks about right to me. @seth could you check it too?

Here's the correct (public) pattern library link: https://github.com/ushahidi/platform-pattern-library/blob/master/assets/templates/_Modals.hbs#L1216-L1235

**Comment by rjmackay** [comment]
> Is the main reason for replacing the old with the new is that the old does not allow for the user to scroll if the list is longer than the space provided?

Honestly... I'm not 100% sure when this was changed in the pattern library. But I think you're correct that was the primary reason. On a small screen the current UI for picking a surveys gets weird with lots of surveys.

**Comment by middle8media** [comment]
@ryanchristo thanks man! I'll take a look in the morning.

Yes, the menu was revised because of scrolling constraints but never made it's way into the client.

**Comment by rjmackay** [comment]
@ryanchristo If you take a look at the pattern library link, you can see the markup is a bit different. This also uses a new `mainsheet` pattern that we haven't used in the client yet. I think its pretty similar to the modal... but I'm not 100% sure.

Unfortunately that makes this a bit more work to get implemented

**Comment by ryanchristo** [comment]
@rjmackay Updated. Still trying to figure out a couple minor styling inconsistencies but I created a new mainsheet service and container based off the modal service and container.

![](http://recordit.co/2cst2K1KRl.gif)

**Comment by Angamanga** [comment]
@ryanchristo And again, thank you soo much for your contribution!! I have added a review for the pr connected to this issue, a few minor fixes and a suggestion for how to fix the last styling-issues.

**Comment by ryanchristo** [comment]
@middle8media @Angamanga Thank you! I made the requested changes and will be happy to make any further adjustments.
