### ISSUE TITLE
Create standalone 'Create post' view

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#698]
### Expected behaviour
I can link directly to the "Create post" list of surveys

### Actual behaviour
I can only link to map or timeline view

### Steps to reproduce the behaviour/error

This should use the create post modal
<img width="452" alt="screenshot 2017-07-27 14 22 27" src="https://user-images.githubusercontent.com/7965/28651813-347fa18a-72d8-11e7-9d39-c0fec2da7475.png">

This is built in https://github.com/ushahidi/platform-client/issues/696

**Comment by rjmackay** [comment]
It looks like the styles for this might not work outside of a mainsheet. @middle8media could you take a look at making these styles work on a standalone page? (or suggest different patterns if that works)

**Comment by Angamanga** [comment]
Tech-spec:
- [ ] add route `/post/create` to post-routes.js
- [ ] resolve allowed forms from PostSurveyService in the route
- [ ] add a controller that open/close the modal

**Comment by rjmackay** [comment]
@Angamanga for a quick version, I'm not sure I'd even open this in a modal. Rather put the list into the main body. However I'm not sure if we have styles that work for that.

**Comment by rjmackay** [comment]
>  resolve allowed forms from PostSurveyService in the route

I'd actually prefer we don't resolve things in the route. It makes it harder to see where things come from, and harder to handle an error sensibly

**Comment by Angamanga** [comment]
@rjmackay I found a better way of handling this by using the existing `/view/:view` route and adjusting existing controller rather than creating a new one.

**Comment by caharding** [comment]
@Angamanga can we change the text to "Submit a report"

**Comment by Angamanga** [comment]
@caharding This would mean changing the text to the box that appears when a user clicks on the yellow + sign too. Do we really want to do that? We are not using the word report anywhere else?
