### ISSUE TITLE
tiny bug with sub-category check marks being on even though they are filtered "off"

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-client#713]
This is happening on both live site and sandbox. cc: @willdoran 

I don't know how to explain this besides a gif....
https://d.pr/i/6kNRkk

**Comment by middle8media** [comment]
@jshorland are you referring to the animation?

**Comment by middle8media** [comment]
The survey filter subcats are not getting the `checked` class applied when the parent category is checked.
@willdoran @rjmackay can you add this fix to the client?

 If `checked` is correctly applied to the subcats the style should look like this: 

```
<div class="form-field checkbox checked">
    <label>Verified</label>
</div>

<div class="form-field checkbox checked">
    <label>Unverified</label>
</div>

etc...
```
![image](https://user-images.githubusercontent.com/1033332/29088047-f5d9a83c-7c45-11e7-9f2f-e28be2c5da63.png)

and if on of the subcats is unchecked it would be styled like so:

![image](https://user-images.githubusercontent.com/1033332/29093125-b9d52b66-7c56-11e7-8e82-a0c8ed182539.png)

I have pushed a fix to this in the PL and published v3.7.1-rc.15 to npm

**Comment by willdoran** [comment]
I can add this, I'll do it now

**Comment by middle8media** [comment]
Thanks @willdoran hopefully it is a quick fix.

**Comment by willdoran** [comment]
done

**Comment by willdoran** [comment]
It's sitting in PRs now
