### ISSUE TITLE
[dev-issue] "more"  toggle dropdown icon is broken

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform-client#783]
### Expected behaviour
I can see a "More" icon as in the designs
### Actual behaviour
I see only part of the icon. 

<img width="559" alt="bug-toggle-more-button-barely-visible" src="https://user-images.githubusercontent.com/2434401/31259678-f9fec08a-aa1e-11e7-9475-f7a29b7e9baf.png">

**Comment by rowasc** [comment]
@Angamanga can you take a look?  it seems to come from PL 
Thanks!

**Comment by Angamanga** [comment]
@rowasc Its a known issue so @middle8media is on it. Taken care of here: https://github.com/ushahidi/platform-pattern-library/pull/152

**Comment by rjmackay** [comment]
Assuming done
