### ISSUE TITLE
Cannot structure posts when in post-detail view

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform-client#901]
### Expected behaviour
I should be able to edit and then add a post to a survey (and then continue editing/structuring it) when in the post detail view
### Actual behaviour
When in post detail view, I select edit and then try to add the post to a survey, but I get the validation error and the http response is `422 Unprocessable Entity`
![edit-post-detail-view-error](https://user-images.githubusercontent.com/8941223/32195281-3d3a8460-bd93-11e7-9895-7fa5e49528b8.gif)

### Steps to reproduce the behaviour/error
Select a post and view it in post detail view, select edit, try to add it to a survey

**Comment by Angamanga** [comment]
related to #2116

**Comment by rjmackay** [comment]
So in data view this now happens as part of 'edit' mode right?
Could we do the same here? or simply link to edit view within data mode?
I don't think we should maintain 2 different ways to structure a post.

@Justin-Scherer any objection to just removing the UI for 'Add this post to a survey' from the detail view and link 'edit' directly to data view?

**Comment by crcommons** [comment]
I spoke with Justin about this and he had some reasonable objections. Will
link up with you on this asap.

**Comment by justinscherer** [comment]
Related to https://github.com/ushahidi/platform/issues/2116

Let me know if something else is needed to fix the issue.

**Comment by crcommons** [comment]
Closing in favor of: https://zube.io/ushahidi/platform/c/3453
