### ISSUE TITLE
'Post' stage is separate from structure in edit screen

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-client#96]
Core post fields are being shown as their own 'step' in the post edit screen, rather than part of the first step.
https://www.dropbox.com/s/j2smhafn2kylwn6/Screenshot%202016-02-22%2015.55.38.png?dl=0

Post and structure should just be 1 step here (as when fields are displayed on post detail)

**Comment by willdoran** [comment]
This is done and merged into develop.
